/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monster.glb 
Author: Catholomew (https://sketchfab.com/Catholomew)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/asylum-demon-dark-souls-effe21bad5bf4c37a0ea1941aa8b8985
Title: Asylum Demon - Dark Souls
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Monster(props) {

  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/monster.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
  if (!actions) return;

  const first = Object.values(actions)[0]; // pick first animation
  first?.reset().fadeIn(0.5).play();

  return () => first?.fadeOut(0.5);
}, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.228}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="c2230_500" position={[-0.106, 0, 0.07]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="c2230_Mesh_498" />
                  <group name="c2230_Mesh001_499" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.c2230_0__C_DullLeatherDSB__c2230} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.c2230_0__C_DullLeatherDSB__c2230_V1} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.c2230_1__C_WetDSB__c2230} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.c2230_2__C_DullLeatherDSB_Edge__c2230} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.WP_A_0653_2_4__P_DullLeatherDSB__c2230} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.WP_A_0653_2_4__P_DullLeatherDSB__c2230} skeleton={nodes.Object_13.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/monster.glb')
